import { DEFAULT_PORTFOLIO_MEDIA_SETTINGS, type PortfolioContent } from "@/utils/portfolio";

export const samplePortfolioContent: PortfolioContent = {
  name: "Maya Rao",
  profileImageUrl: "/marketing/portfolio/profile.jpg",
  profileImageSourceUrl: "/marketing/portfolio/profile.jpg",
  showProfileImage: true,
  tagline: "Maya Rao — Selected work",
  headline: "Independent product designer building calm, useful software.",
  bio: "I help small teams shape focused products and ship dependable experiences.",
  location: "Bengaluru, India",
  availability: "Available for select engagements",
  contactEmail: "",
  social: [],
  projects: [
    {
      id: "chitra-brand",
      title: "Chitra — Brand and interface system",
      description: "A complete identity and component library for a photography platform.",
      role: "Product design",
      year: "2025",
      url: "",
      imageUrl: "/marketing/portfolio/project-1.jpg",
      client: "Chitra",
      timeline: "8 weeks",
      deliverables: ["Brand strategy", "Design system", "UI kit"],
      visibility: "public",
      challenge: "",
      solution: "",
      outcome: "",
      tools: ["Figma", "React", "Tailwind"],
    },
    {
      id: "ledger-dashboard",
      title: "Ledger — Finance dashboard",
      description: "A focused dashboard for tracking revenue, expenses, and client obligations.",
      role: "UI / UX design",
      year: "2024",
      url: "",
      imageUrl: "/marketing/portfolio/project-2.jpg",
      client: "Ledger",
      timeline: "12 weeks",
      deliverables: ["UX research", "Wireframes", "High-fidelity UI"],
      visibility: "public",
      challenge: "",
      solution: "",
      outcome: "",
      tools: ["Figma", "Miro", "Notion"],
    },
  ],
  services: [],
  testimonials: [],
  sections: [
    { key: "about", visible: false },
    { key: "projects", visible: true },
    { key: "services", visible: false },
    { key: "testimonials", visible: false },
    { key: "contact", visible: false },
  ],
  practices: [],
  practiceLayout: "unified",
  mediaSettings: DEFAULT_PORTFOLIO_MEDIA_SETTINGS,
};
