export const contactContent = {
  eyebrow: "ONE INBOX",
  title: "Bring us the part of the work that refuses to stay connected.",
  intro: "Questions, support, press, partnerships, or a workflow that keeps breaking. Give us the concrete version; it reaches the people building Rive.",
  asideTitle: "Write directly",
  asideBody: "For questions, support, press, or anything else that needs a human answer.",
  email: "hello@rive.work",
  form: {
    nameLabel: "Name",
    namePlaceholder: "Your name",
    emailLabel: "Email",
    emailPlaceholder: "you@email.com",
    subjectLabel: "Subject",
    subjects: ["General Inquiry", "Partnership", "Press", "Feedback", "Bug Report"],
    messageLabel: "Message",
    messagePlaceholder: "Tell us what happened, what you expected, and where the context broke.",
    submitLabel: "Send message",
    submittingLabel: "Sending…",
    successTitle: "Message received.",
    successBody: "A human will reply within 24 hours.",
    fallbackError: "Your message could not be sent.",
  },
} as const;
